SET SQL DIALECT 3;

CREATE DATABASE 'C:\u1\facultad\base de datos\db\Bd_guia1.FDB'
PAGE_SIZE 1024
DEFAULT CHARACTER SET ;
/* Domain definitions */
CREATE DOMAIN "CUIT" AS VARCHAR(11);
CREATE DOMAIN "D_MES" AS SMALLINT
	 check(value >= 1 or value <= 12);
CREATE DOMAIN "TIPO_FACTURAS" AS VARCHAR(3)
	 CHECK (VALUE IN('A','B','NCA','NCB'));
CREATE DOMAIN "TIPO_PERSONA" AS VARCHAR(1)
	 CHECK (VALUE IN('F','J'));
CREATE DOMAIN "USUARIO" AS VARCHAR(20)
	 DEFAULT USER;

/* Table: CLIENTES, Owner: SYSDBA */

CREATE TABLE "CLIENTES" 
(
  "CUIT"	 CUIT  NOT NULL,
  "NOMBRE"	 VARCHAR(40) NOT NULL,
  "SITUACION_IVA"	 VARCHAR(2),
  "TIPO_PERSONA"	 VARCHAR(1),
  "CALLE"	 VARCHAR(30) NOT NULL,
  "NUMERO_PUERTA"	 VARCHAR(6),
  "PISO"	 VARCHAR(2),
  "DPTO"	 VARCHAR(2),
  "CODIGO_POSTAL"	 VARCHAR(8),
  "FECHA_BAJA"	 DATE,
 PRIMARY KEY ("CUIT")
);

/* Table: COMPETENCIA, Owner: SYSDBA */

CREATE TABLE "COMPETENCIA" 
(
  "CUIT"	 VARCHAR(11) NOT NULL,
  "NOMBRE"	 VARCHAR(50),
 PRIMARY KEY ("CUIT")
);

/* Table: FACTURAS, Owner: SYSDBA */

CREATE TABLE "FACTURAS" 
(
  "TIPO"	 SMALLINT NOT NULL,
  "NUMERO"	 INTEGER NOT NULL,
  "FECHA"	 DATE,
  "CUIT"	 CUIT ,
  "CANT_ITEMS"	 INTEGER,
 PRIMARY KEY ("TIPO", "NUMERO")
);

/* Table: FACTURAS_ITEMS, Owner: SYSDBA */

CREATE TABLE "FACTURAS_ITEMS" 
(
  "FACTURA_TIPO"	 SMALLINT NOT NULL,
  "FACTURA_NUMERO"	 INTEGER NOT NULL,
  "PRODUCTO_CODIGO"	 SMALLINT NOT NULL,
  "CANTIDAD"	 NUMERIC(8,2) NOT NULL,
  "PRECIO"	 NUMERIC(8,2) NOT NULL,
  "DESCUENTO_PORCENTAJE"	 NUMERIC(3,2),
 PRIMARY KEY ("FACTURA_TIPO", "FACTURA_NUMERO", "PRODUCTO_CODIGO")
);

/* Table: LOCALIDADES, Owner: SYSDBA */

CREATE TABLE "LOCALIDADES" 
(
  "CODIGO_POSTAL"	 VARCHAR(8) NOT NULL,
  "LOCALIDAD"	 VARCHAR(25) NOT NULL,
  "PROVINCIA_ID"	 SMALLINT NOT NULL,
 PRIMARY KEY ("CODIGO_POSTAL")
);

/* Table: PRECIOS_COMPETENCIA, Owner: SYSDBA */

CREATE TABLE "PRECIOS_COMPETENCIA" 
(
  "CUIT"	 VARCHAR(11) NOT NULL,
  "PRODUCTO_CODIGO"	 INTEGER,
  "FECHA"	 DATE,
  "PRECIO"	 NUMERIC(8,2)
);

/* Table: PRODUCTOS, Owner: SYSDBA */

CREATE TABLE "PRODUCTOS" 
(
  "CODIGO"	 SMALLINT NOT NULL,
  "NOMBRE"	 VARCHAR(20) NOT NULL,
  "FAMILIA"	 VARCHAR(1) NOT NULL,
  "PRECIO"	 NUMERIC(8,2),
  "CANTIDAD_BULTO"	 SMALLINT,
 PRIMARY KEY ("CODIGO")
);

/* Table: PROVINCIAS, Owner: SYSDBA */

CREATE TABLE "PROVINCIAS" 
(
  "ID"	 SMALLINT NOT NULL,
  "NOMBRE"	 VARCHAR(20) NOT NULL,
 PRIMARY KEY ("ID")
);

/* Table: SITUACIONES_IVA, Owner: SYSDBA */

CREATE TABLE "SITUACIONES_IVA" 
(
  "ABREVIATURA"	 VARCHAR(2) NOT NULL,
  "DESCRIPCION"	 VARCHAR(30) NOT NULL,
 PRIMARY KEY ("ABREVIATURA")
);
ALTER TABLE "CLIENTES" ADD FOREIGN KEY ("SITUACION_IVA") REFERENCES "SITUACIONES_IVA" ("ABREVIATURA") ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE "FACTURAS" ADD FOREIGN KEY ("CUIT") REFERENCES "CLIENTES" ("CUIT") ON UPDATE CASCADE ON DELETE NO ACTION;
ALTER TABLE "FACTURAS_ITEMS" ADD FOREIGN KEY ("PRODUCTO_CODIGO") REFERENCES "PRODUCTOS" ("CODIGO") ON UPDATE CASCADE ON DELETE NO ACTION;
ALTER TABLE "FACTURAS_ITEMS" ADD FOREIGN KEY ("FACTURA_TIPO", "FACTURA_NUMERO") REFERENCES "FACTURAS" ("TIPO", "NUMERO") ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "LOCALIDADES" ADD FOREIGN KEY ("PROVINCIA_ID") REFERENCES "PROVINCIAS" ("ID") ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE "PRODUCTOS" ADD
CHECK (FAMILIA IN ('A','B','C'));

ALTER TABLE "PRODUCTOS" ADD
CHECK (FAMILIA IN ('A','B','C'));


/* Grant Roles for this database */


/* Grant permissions for this database */

