#!/bin/bash
rm hello.so
rm hello.o
#python2
#gcc -shared -fPIC -I/usr/include/python2.7 -c hello.c
#gcc -shared -L/usr/lib/python2.7/config-x86_64-linux-gnu -lpython2.7 -o hello.so hello.o

gcc -shared -fPIC -I/usr/include/python3.3m -c hello.c
gcc -shared -L/usr/lib/x86_64-linux-gnu/ -lpython3.3m -o hello.so hello.o
