include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = t5
t5_OBJC_FILES = main.m AppController.m window.m gview.m
t5_HEADERS = AppController.h window.h gview.h
t5_RESOURCE_FILES = t5.plist
t5_APPLICATION_ICON = MyApp.png
t5_RESOURCE_FILES = MyApp.png

include $(GNUSTEP_MAKEFILES)/application.make

